import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import BreezySwing.*;

public class AddStudentDialog extends GBDialog {

	private JLabel addLabel = addLabel("Add Student:",1,1,1,1);
	
	private ButtonGroup studentTypeBG = new ButtonGroup();
	private JRadioButton undergradButton = addRadioButton("Undergraduate",2,1,1,1);
	private JRadioButton graduateButton = addRadioButton("Graduate",2,2,1,1);
	
	private JLabel nameLabel = addLabel("Name:",3,1,1,1);
	private JTextField nameField = addTextField("",3,2,1,1);
	
	private JLabel idLabel = addLabel("Student ID(0 for autogenerated):",4,1,1,1);
	private IntegerField idField = addIntegerField(0,4,2,1,1);
	
	private JLabel majorLabel = addLabel("Major:",5,1,1,1);
	private JTextField majorField = addTextField("",5,2,1,1);
	
	private JLabel levelLabel = addLabel("Level:",6,1,1,1);
	private JComboBox<String> comboLevel = addComboBox(6,2,1,1);
	
	private JButton addStudentButton = addButton("Add Undergraduate",7,2,1,1);
	
	private Database db;
	
	public void buttonClicked(JButton button) {
		if(button == addStudentButton) {
			
			String name = nameField.getText();
			if(name.isEmpty() || isBlank(name)) {
				messageBox("Empty name");
				return;
			}
			
			String major = majorField.getText();
			if(major.isEmpty() || isBlank(major)) {
				messageBox("Empty major");
				return;
			}
			
			if(undergradButton.isSelected()) {
				//undergrad
				if(comboLevel.getSelectedItem().equals("Freshmen")) {
					db.addPerson(new Undergraduate(name, 0, Undergraduate.Grade.FRESHMAN, major));
				}else if(comboLevel.getSelectedItem().equals("Sophmore")) {
					db.addPerson(new Undergraduate(name, 0, Undergraduate.Grade.SOPHMORE, major));
				}else if(comboLevel.getSelectedItem().equals("Junior")) {
					db.addPerson(new Undergraduate(name, 0, Undergraduate.Grade.JUNIOR, major));
				}else if(comboLevel.getSelectedItem().equals("Senior")) {
					db.addPerson(new Undergraduate(name, 0, Undergraduate.Grade.SENIOR, major));
				}
			}else {
				//grad
				db.addPerson(new GraduateStudent(name, 0, major));
			}
		}
	}
	
	//error checking helper method
	private boolean isBlank(String s) {
		for(int i = 0; i < s.length(); i++) {
			if(!Character.isWhitespace(s.charAt(i))) return false;
		}
		return true;
	}
	
	private ChangeListener cl = new ChangeListener() {
		
		@Override
		public void stateChanged(ChangeEvent e) {
			JRadioButton source = (JRadioButton) e.getSource();
			
			if(source.getText().equals("Undergraduate") && undergradButton.isSelected()) {
				//undergrad --> show level field
				idField.setVisible(true);
				idLabel.setVisible(true);
				majorField.setVisible(true);
				majorLabel.setVisible(true);
				comboLevel.setVisible(true);
				levelLabel.setVisible(true);
				addStudentButton.setText("Add Undergraduate Student");
			}else if(source.getText().equals("Graduate") && graduateButton.isSelected()){
				//grad --> hide level field
				idField.setVisible(true);
				idLabel.setVisible(true);
				majorField.setVisible(true);
				majorLabel.setVisible(true);
				comboLevel.setVisible(false);
				levelLabel.setVisible(false);
				addStudentButton.setText("Add Graduate Student");
			}
			
		}
	};
	
	
	public AddStudentDialog(JFrame parent, Database d) {
		super(parent);
		studentTypeBG.add(graduateButton);
		studentTypeBG.add(undergradButton);
		comboLevel.addItem("Freshmen");
		comboLevel.addItem("Sophmore");
		comboLevel.addItem("Junior");
		comboLevel.addItem("Senior");
		comboLevel.setSelectedIndex(0);
		
		graduateButton.addChangeListener(cl);
		undergradButton.addChangeListener(cl);
		
		undergradButton.setSelected(true);
		
		db = d;
		
		this.setSize(400,400);
		this.setTitle("Add Student");
		this.setVisible(true);
		
	}

}
